### ISSUE TITLE
Another crash in building a framework

### ISSUE THREAD

**Issue by iamleeg** [gnustep/libs-xcode#10]
This is in a heavily patched version of the project described in #8 and with the patch from #9 merged in so it's not that easy to give steps to repro, but I think the description indicates what's going on:

Having successfully built the framework sources, the framework build phase fails because `-[PBXFrameworksBuildPhase generateDummyClass]` expects `GNUSTEP_SYSTEM_ROOT` to be set in the environment, but in my case it isn't. I have tools-make (actually from git but the version reported is 2.9.0) and I have sourced `GNUstep.sh`, it just doesn't define that variable.

I think the correct behaviour can be obtained with this version of -make by finding the value of `GNUSTEP_SYSTEM_LIBRARY` and appending the path component `@"Frameworks"`. I also think that if the value isn't in the environment, then `libs-xcode` should try running `gnustep-config --variable=GNUSTEP_SYSTEM_LIBRARY` to find it.

(BTW why not `GNUSTEP_LOCAL_LIBRARY`?)

**Comment by gcasa** [comment]
I have submitted a fix for this that works for me.  Please verify.  Reopen if the fix doesn't work for you.
